"""add_ebpf_correction_fields

Revision ID: c2343e8e8bb0
Revises: 4ef7c9b5a210
Create Date: 2026-06-13 02:12:48.461079

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c2343e8e8bb0'
down_revision: str | None = '4ef7c9b5a210'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    columns = {item["name"] for item in sa.inspect(bind).get_columns("vulnerability")}
    if "llm_original_type" not in columns:
        op.add_column('vulnerability', sa.Column('llm_original_type', sa.String(length=100), nullable=True, comment='LLM初始分类(若被eBPF纠正则保留此字段)'))
    if "ebpf_corrected" not in columns:
        op.add_column('vulnerability', sa.Column('ebpf_corrected', sa.Boolean(), nullable=True, comment='是否被eBPF运行时证据纠正分类'))
        op.execute("UPDATE vulnerability SET ebpf_corrected = false WHERE ebpf_corrected IS NULL")
        op.alter_column('vulnerability', 'ebpf_corrected', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerability', 'ebpf_corrected')
    op.drop_column('vulnerability', 'llm_original_type')
    # ### end Alembic commands ###
